name: Hui's Page
description: Happy coding!!!
meta_description: "..."

markdown: kramdown
highlighter: pygments
logo: false
cover: '/assets/images/cover.jpg'
paginate: 10
baseurl: /
domain_name: 'http://hchim.github.io'
google_analytics: 'UA-XXXXXXXX-X'
mathjax: true

gems: [jekyll-paginate]

navigation:
  - label: Home
    url: /
  - label: About
    url: /about.html
  - label: Useful Links
    url: /links.html

# Details for the RSS feed generator
url: 'http://hchim.github.io'
author: 'Hui Chen'
bio: 'I am a software engineer!'
location: Beatiful Irvine
website: http://hchim.github.io

# disque
disqus: true
disqus_shortname: huis-page
