# Site settings
name: Hui's Page
description: 'Happy coding!!!'

markdown: kramdown
highlighter: pygments
logo: false
paginate: 5
baseurl: /
domain_name: 'http://blog.hch.im'
gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            'http://blog.hch.im'
author:         'Hui Chen'
biography:      'undefined'

# post configs
disqus: true
archive: true

